name: Build frontend app

on:
  pull_request:
    paths:
      - 'app/**'
      - '.github/workflows/frontend-build.yml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: '22'
      - name: Install dependencies (ci)
        run: npm ci
      - name: Build application
        run: npm run build
