name: Build frontend app

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'app/**'
      - '.github/workflows/frontend-build.yml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: '22'
      - name: Install dependencies (ci)
        run: npm ci
      - name: Build application
        run: npm run build
      - name: compile application
        run: npm run test 
      - name: audit application
        run: npm audit --audit-level=high
                - name: Call webhook (POST)
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -s -X POST -H 'Content-Type: application/json' \
            -d '{"content":"Build status: ✅","username": "$GITHUB_REPOSITORY"}' \
            "$WEBHOOK_URL"
